-- MySQL Script generated by MySQL Workbench
-- 06/22/15 13:33:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blast
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blast` DEFAULT CHARACTER SET latin1 ;
USE `blast` ;

-- -----------------------------------------------------
-- Table `blast`.`SOURCE_SEQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blast`.`SOURCE_SEQ` (
  `seq-id` VARCHAR(100) NOT NULL DEFAULT '',
  `match-found-bool` TINYINT(1) NULL DEFAULT NULL,
  `nucleotide-sequence` VARCHAR(5000) NULL DEFAULT NULL,
  PRIMARY KEY (`seq-id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blast`.`BLAST_RESULT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blast`.`BLAST_RESULT` (
  `SOURCE_SEQ_seq-id` VARCHAR(100) NOT NULL,
  `amount-hits` INT(11) NULL DEFAULT NULL,
  `result1-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result1-alignment-score` FLOAT NULL DEFAULT NULL,
  `result1-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result1-E-value` FLOAT NULL DEFAULT NULL,
  `result1-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result2-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result2-alignment-score` FLOAT NULL DEFAULT NULL,
  `result2-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result2-E-value` FLOAT NULL DEFAULT NULL,
  `result2-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result3-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result3-alignment-score` FLOAT NULL DEFAULT NULL,
  `result3-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result3-E-value` FLOAT NULL DEFAULT NULL,
  `result3-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result4-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result4-alignment-score` FLOAT NULL DEFAULT NULL,
  `result4-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result4-E-value` FLOAT NULL DEFAULT NULL,
  `result4-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result5-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result5-alignment-score` FLOAT NULL DEFAULT NULL,
  `result5-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result5-E-value` FLOAT NULL DEFAULT NULL,
  `result5-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result6-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result6-alignment-score` FLOAT NULL DEFAULT NULL,
  `result6-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result6-E-value` FLOAT NULL DEFAULT NULL,
  `result6-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result7-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result7-alignment-score` FLOAT NULL DEFAULT NULL,
  `result7-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result7-E-value` FLOAT NULL DEFAULT NULL,
  `result7-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result8-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result8-alignment-score` FLOAT NULL DEFAULT NULL,
  `result8-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result8-E-value` FLOAT NULL DEFAULT NULL,
  `result8-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result9-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result9-alignment-score` FLOAT NULL DEFAULT NULL,
  `result9-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result9-E-value` FLOAT NULL DEFAULT NULL,
  `result9-ident-percentage` INT(11) NULL DEFAULT NULL,
  `result10-accession-code` VARCHAR(2000) NULL DEFAULT NULL,
  `result10-alignment-score` FLOAT NULL DEFAULT NULL,
  `result10-query-coverage-percentage` INT(11) NULL DEFAULT NULL,
  `result10-E-value` FLOAT NULL DEFAULT NULL,
  `result10-ident-percentage` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SOURCE_SEQ_seq-id`),
  CONSTRAINT `fk_BLAST_RESULT_SOURCE_SEQ1`
    FOREIGN KEY (`SOURCE_SEQ_seq-id`)
    REFERENCES `blast`.`SOURCE_SEQ` (`seq-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blast`.`MATCH_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blast`.`MATCH_INFO` (
  `SOURCE_SEQ_seq-id` VARCHAR(100) NOT NULL,
  `match-found-bool` TINYINT(1) NULL DEFAULT NULL,
  `match-order` VARCHAR(20) NULL DEFAULT NULL,
  `match-family` VARCHAR(20) NULL DEFAULT NULL,
  `match-genus` VARCHAR(20) NULL DEFAULT NULL,
  `match-species` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`SOURCE_SEQ_seq-id`),
  CONSTRAINT `fk_MATCH_INFO_SOURCE_SEQ1`
    FOREIGN KEY (`SOURCE_SEQ_seq-id`)
    REFERENCES `blast`.`SOURCE_SEQ` (`seq-id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blast`.`SIMILAR_PROTEIN_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blast`.`SIMILAR_PROTEIN_INFO` (
  `SOURCE_SEQ_seq-id` VARCHAR(100) NOT NULL,
  `similarity-found-bool` TINYINT(1) NULL DEFAULT NULL,
  `accession-code-protein` VARCHAR(45) NULL DEFAULT NULL,
  `match-percentage` INT(11) NULL DEFAULT NULL,
  `protein-order` VARCHAR(45) NULL DEFAULT NULL,
  `protein-family` VARCHAR(45) NULL DEFAULT NULL,
  `protein-genus` VARCHAR(45) NULL DEFAULT NULL,
  `protein-species` VARCHAR(45) NULL DEFAULT NULL,
  `protein-function` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`SOURCE_SEQ_seq-id`),
  CONSTRAINT `fk_SIMILAR_PROTEIN_INFO_SOURCE_SEQ`
    FOREIGN KEY (`SOURCE_SEQ_seq-id`)
    REFERENCES `blast`.`SOURCE_SEQ` (`seq-id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
